# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pulp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pulp
  pod 'SnapKit', '~> 4.0.0'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FBSDKShareKit'
  pod 'FacebookShare'	
  pod 'MapKitGoogleStyler'
  pod 'Bolts', "~> 1.9.0"
  
  pod 'Moya', '~> 12.0.1'

end