# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Pulp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Pulp
  pod 'SnapKit', '~> 4.0.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod "MapKitGoogleStyler"
  
  pod 'Moya', '~> 12.0.1'

end
